# Generated by Django 5.0 on 2024-01-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trombinoscoop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='test',
        ),
    ]
