# Generated by Django 5.0 on 2024-01-15 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trombinoscoop', '0002_remove_personne_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('adresse_postale', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Cursus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('couleur', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='personne',
            name='mot_de_passe',
        ),
        migrations.AddField(
            model_name='personne',
            name='amis',
            field=models.ManyToManyField(blank=True, to='Trombinoscoop.personne'),
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Trombinoscoop.personne')),
                ('annee', models.IntegerField()),
                ('cursus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trombinoscoop.cursus')),
            ],
            bases=('Trombinoscoop.personne',),
        ),
        migrations.AddField(
            model_name='personne',
            name='faculte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Trombinoscoop.faculte'),
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Trombinoscoop.personne')),
                ('bureau', models.CharField(max_length=30)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Trombinoscoop.campus')),
                ('fonction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Trombinoscoop.fonction')),
            ],
            bases=('Trombinoscoop.personne',),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_de_publication', models.DateField()),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Trombinoscoop.personne')),
            ],
        ),
    ]
