# Generated by Django 5.0 on 2024-02-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trombinoscoop', '0004_personne_mot_de_passe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='contenu',
            new_name='conteu',
        ),
    ]
